on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "**/Cargo.lock"
      - "**/Cargo.toml"

name: Publish crate

jobs:
  release:
    name: Publish crate
    env:
      PROJECT_NAME: self-assessment
    runs-on: ubuntu-latest
    steps:
      - uses: katyo/publish-crates@v1
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
